### ISSUE TITLE
Rerunning container playbook with --new option in generate_systemd results in failure if the service is started

### ISSUE THREAD

**Issue by zephyros-dev** [containers/ansible-podman-collections#345] opened 2021-11-26 14:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind bug

**Description**

Rerunning container playbook with --new option in generate_systemd results in failure if the service is started.

**Steps to reproduce the issue:**

1. Run a playbook with --new options in generate systemd and enable the systemd afterward
```
- hosts: localhost
  tasks:
    - name: HTTP Echo Container
      containers.podman.podman_container:
        name: "echo-test"
        image: "mendhak/http-https-echo:latest"
        ports:
          - "8080:80"
        generate_systemd:
          container_prefix: ""
          pod_prefix: ""
          separator: ""
          path: "/home/{{ ansible_user }}/.config/systemd/user"
          new: yes
        state: "started"

    - name: "Enable systemd service"
      ansible.builtin.systemd:
        daemon_reload: yes
        enabled: yes
        name: echo-test
        scope: user
        state: started
      register: service
```
2. The first run will work normally

**Describe the results you received:**
- The second run will consistently return the following error
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Can't delete container echo-test", "stderr": "Error: no container with name or ID \"echo-test\" found: no such container\n", "stderr_lines": ["Error: no container with name or ID \"echo-test\" found: no such container"], "stdout": "", "stdout_lines": []}
```
**Describe the results you expected:**
- The second runs produce the container normally

**Additional information you deem important (e.g. issue happens only occasionally):**
- After the second run, no container can be found using podman ps -a
- The third run will consistently works exactly as the first run (state is changed, systemd file is created)
  - Due to this, a workaround can be made by using ansible retries. Example using the above playbook:
```
- hosts: localhost
  tasks:
    - name: HTTP Echo Container
      containers.podman.podman_container:
        name: "echo-test"
        image: "mendhak/http-https-echo:latest"
        ports:
          - "18080:80"
        generate_systemd:
          container_prefix: ""
          pod_prefix: ""
          separator: ""
          path: "/home/{{ ansible_user }}/.config/systemd/user"
          new: yes
        state: "started"
      # Retries until container run successfully
      register: container
      until: container.failed == false

    - name: "Enable systemd service"
      ansible.builtin.systemd:
        daemon_reload: yes
        enabled: yes
        name: echo-test
        scope: user
        state: started
      register: service
      until: service.failed == false
```
- The systemd file still exists and can be started normally

**Version of the `containers.podman` collection:**
**Either git commit if installed from git: `git show --summary`**
**Or version from `ansible-galaxy` if installed from galaxy: `ansible-galaxy collection list | grep containers.podman`**

```
containers.podman 1.8.3  
```

**Output of `ansible --version`:**

```
ansible [core 2.11.6] 
  config file = /home/phong/production/infra/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)]
  jinja version = 3.0.3
  libyaml = True
```

**Output of `podman version`:**

```
podman version 3.4.2
```

**Output of `podman info --debug`:**

```
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: conmon-2.0.30-2.fc35.x86_64
    path: /usr/bin/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 8
  distribution:
    distribution: fedora
    variant: server
    version: "35"
  eventLogger: journald
  hostname: server
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1000
      size: 1
    - container_id: 1
      host_id: 100000
      size: 65536
  kernel: 5.14.18-300.fc35.x86_64
  linkmode: dynamic
  logDriver: journald
  memFree: 15094743040
  memTotal: 33328046080
  ociRuntime:
    name: crun
    package: crun-1.3-1.fc35.x86_64
    path: /usr/bin/crun
    version: |-
      crun version 1.3
      commit: 8e5757a4e68590326dafe8a8b1b4a584b10a1370
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    exists: true
    path: /run/user/1000/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: true
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: slirp4netns-1.1.12-2.fc35.x86_64
    version: |-
      slirp4netns version 1.1.12
      commit: 7a104a101aa3278a2152351a082a6df71f57c9a3
      libslirp: 4.6.1
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.3
  swapFree: 8589930496
  swapTotal: 8589930496
  uptime: 2h 17m 33.67s (Approximately 0.08 days)
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - registry.fedoraproject.org
  - registry.access.redhat.com
  - quay.io
store:
  configFile: /home/user/.config/containers/storage.conf
  containerStore:
    number: 0
    paused: 0
    running: 0
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: fuse-overlayfs-1.7.1-2.fc35.x86_64
      Version: |-
        fusermount3 version: 3.10.5
        fuse-overlayfs: version 1.7.1
        FUSE library version 3.10.5
        using FUSE kernel interface version 7.31
  graphRoot: /home/user/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: btrfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 57
  runRoot: /run/user/1000/containers
  volumePath: /home/user/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 1636748737
  BuiltTime: Sat Nov 13 03:25:37 2021
  GitCommit: ""
  GoVersion: go1.16.8
  OsArch: linux/amd64
  Version: 3.4.2
```

**Package info (e.g. output of `rpm -q podman` or `apt list podman`):**

```
podman-3.4.2-1.fc35.x86_64
```

**Playbok you run with ansible (e.g. content of `playbook.yaml`):**

```
(paste your output here)
```

**Command line and output of ansible run with high verbosity**

**Please NOTE: if you submit a bug about idempotency, run the playbook with `--diff` option, like:**

`ansible-playbook -i inventory --diff -vv playbook.yml`

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Can't delete container echo-test", "stderr": "Error: no container with name or ID \"echo-test\" found: no such container\n", "stderr_lines": ["Error: no container with name or ID \"echo-test\" found: no such container"], "stdout": "", "stdout_lines": []}
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 35

**Comment by jooola** [comment] 2021-12-28 15:33
I am facing a similar issue but running a third time does not fix the problem and the workaround isn't working for me.
On my side, the container is running and has the right name.

```yml
- hosts: pod-auk
  become: true
  become_user: podman
  tasks:
    - name: deploy funnel container
      containers.podman.podman_container:
        name: funnel
        image: REDACTED/funnel:latest
        ports:
          - 4000:4000
        env:
          CREDENTIALS: REDACTED
        generate_systemd:
          path: "{{ podman_home }}/.config/systemd/user"
          # new: yes
        state: started

    - name: enable/start funnel container service
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ podman_uid }}"
      systemd:
        name: "container-funnel"
        enabled: true
        state: started
        scope: user
```

```
$ ansible-galaxy collection list | grep containers.podman
containers.podman 1.9.0  

$ ansible --version
ansible 2.10.16
  config file = /home/jo/linux/ansible/ansible.cfg
  configured module search path = ['/home/jo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jo/linux/ansible/venv/lib/python3.9/site-packages/ansible
  executable location = /home/jo/linux/ansible/venv/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
```

```
$ podman --version
podman version 3.4.2

$ podman info --debug
host:
  arch: amd64
  buildahVersion: 1.23.1
  cgroupControllers:
  - memory
  - pids
  cgroupManager: systemd
  cgroupVersion: v2
  conmon:
    package: 'conmon: /usr/libexec/podman/conmon'
    path: /usr/libexec/podman/conmon
    version: 'conmon version 2.0.30, commit: '
  cpus: 2
  distribution:
    codename: bullseye
    distribution: debian
    version: "11"
  eventLogger: journald
  hostname: pod-auk.REDACTED.net
  idMappings:
    gidmap:
    - container_id: 0
      host_id: 1100
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
    uidmap:
    - container_id: 0
      host_id: 1100
      size: 1
    - container_id: 1
      host_id: 231072
      size: 65536
  kernel: 5.10.0-10-amd64
  linkmode: dynamic
  logDriver: journald
  memFree: 1628078080
  memTotal: 2078957568
  ociRuntime:
    name: crun
    package: 'crun: /usr/bin/crun'
    path: /usr/bin/crun
    version: |-
      crun version UNKNOWN
      commit: ea1fe3938eefa14eb707f1d22adff4db670645d6
      spec: 1.0.0
      +SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
  os: linux
  remoteSocket:
    path: /run/user/1100/podman/podman.sock
  security:
    apparmorEnabled: false
    capabilities: CAP_CHOWN,CAP_DAC_OVERRIDE,CAP_FOWNER,CAP_FSETID,CAP_KILL,CAP_NET_BIND_SERVICE,CAP_SETFCAP,CAP_SETGID,CAP_SETPCAP,CAP_SETUID,CAP_SYS_CHROOT
    rootless: true
    seccompEnabled: true
    seccompProfilePath: /usr/share/containers/seccomp.json
    selinuxEnabled: false
  serviceIsRemote: false
  slirp4netns:
    executable: /usr/bin/slirp4netns
    package: 'slirp4netns: /usr/bin/slirp4netns'
    version: |-
      slirp4netns version 1.1.8
      commit: unknown
      libslirp: 4.3.1-git
      SLIRP_CONFIG_VERSION_MAX: 3
      libseccomp: 2.5.1
  swapFree: 1998581760
  swapTotal: 1998581760
  uptime: 11m 5.11s
plugins:
  log:
  - k8s-file
  - none
  - journald
  network:
  - bridge
  - macvlan
  volume:
  - local
registries:
  search:
  - docker.io
  - quay.io
store:
  configFile: /opt/podman/.config/containers/storage.conf
  containerStore:
    number: 1
    paused: 0
    running: 1
    stopped: 0
  graphDriverName: overlay
  graphOptions:
    overlay.mount_program:
      Executable: /usr/bin/fuse-overlayfs
      Package: 'fuse-overlayfs: /usr/bin/fuse-overlayfs'
      Version: |-
        fusermount3 version: 3.10.3
        fuse-overlayfs: version 1.5
        FUSE library version 3.10.3
        using FUSE kernel interface version 7.31
  graphRoot: /opt/podman/.local/share/containers/storage
  graphStatus:
    Backing Filesystem: extfs
    Native Overlay Diff: "false"
    Supports d_type: "true"
    Using metacopy: "false"
  imageStore:
    number: 2
  runRoot: /run/user/1100/containers
  volumePath: /opt/podman/.local/share/containers/storage/volumes
version:
  APIVersion: 3.4.2
  Built: 0
  BuiltTime: Thu Jan  1 01:00:00 1970
  GitCommit: ""
  GoVersion: go1.16.6
  OsArch: linux/amd64
  Version: 3.4.2

```

**Comment by jooola** [comment] 2021-12-28 15:52
I am really not sure if my problem has something to do with this issue.

Still after some digging around, I noticed that the container could not be removed because systemd was automatically spinning it up once the service got stopped by the podman_container module. After stopping the service by hand and running the playbook again, everything worked as expected.

So I am unsure if this is a bug, or a expected behavior.

**Comment by 31239899** [comment] 2022-01-10 03:15
I'm seeing the same error. I think this is happening because the module is removing the container on each run, even when nothing changes. Running the task with `ansible-playbook --check --diff` shows the following on every single run after the first.
```
TASK [create test container] ***************************************************
--- before
+++ after
@@ -1 +1 @@
-rm - True
+rm - False
```
Running without check mode does indeed remove the container. systemd sees that the unit has failed and runs the `ExecStop` command (`podman rm -f --ignore --cidfile=%t/%n.ctr-id`) to restart the unit at the same time as the module tries to `podman rm -f <container>`. See the following system logs:
```
Jan 10 02:12:15 example.com platform-python[597336]: ansible-containers.podman.podman_container Invoked with name=test image=docker.io/vaultwarden/server:alpine generate_systemd={'new': True, 'no_header': True, 'path': '/home/vaultwarden/.config/systemd/user/'} state=present executable=podman detach=True debug=False force_restart=False image_strict=False recreate=False annotation=None authfile=None blkio_weight=None blkio_weight_device=None cap_add=None cap_drop=None cgroup_parent=None cgroupns=None cgroups=None cidfile=None cmd_args=None conmon_pidfile=None
command=None cpu_period=None cpu_rt_period=None cpu_rt_runtime=None cpu_shares=None cpus=None cpuset_cpus=None cpuset_mems=None detach_keys=None device=None device_read_bps=None device_read_iops=None device_write_bps=None device_write_iops=None dns=None dns_option=None dns_search=None entrypoint=None env=None env_file=None env_host=None etc_hosts=None expose=None gidmap=None group_add=None healthcheck=None healthcheck_interval=None healthcheck_retries=None healthcheck_start_period=None healthcheck_timeout=None hostname=None http_proxy=None image_volume=None init=None init_path=None interactive=None ip=None ipc=None kernel_memory=None label=None label_file=None log_driver=None log_level=None log_opt=None mac_address=None memory=None memory_reservation=None memory_swap=None memory_swappiness=None mount=None network=None network_aliases=None no_hosts=None oom_kill_disable=None oom_score_adj=None pid=None pids_limit=None pod=None privileged=None publish=None publish_all=None read_only=None read_only_tmpfs=None restart_policy=None rm=None rootfs=None secrets=NOT_LOGGING_PARAMETER security_opt=None shm_size=None sig_proxy=None stop_signal=None stop_timeout=None subgidname=None subuidname=None sysctl=None systemd=None timezone=None tmpfs=None tty=None uidmap=None ulimit=None user=None userns=None uts=None volume=None volumes_from=None workdir=None
Jan 10 02:12:15 example.com systemd[1131]: Started podman-597363.scope.
Jan 10 02:12:16 example.com systemd[1131]: Started podman-597412.scope.
Jan 10 02:12:16 example.com systemd[1131]: Started podman-597465.scope.
Jan 10 02:12:16 example.com systemd[1131]: Started podman-597515.scope.
Jan 10 02:12:16 example.com platform-python[597336]: ansible-containers.podman.podman_container PODMAN-CONTAINER-DEBUG: podman stop test
Jan 10 02:12:17 example.com systemd[1131]: container-test.service: Main process exited, code=exited, status=143/n/a
Jan 10 02:12:17 example.com systemd[1131]: container-test.service: Failed with result 'exit-code'.
Jan 10 02:12:17 example.com systemd[1131]: Started podman-597612.scope.
Jan 10 02:12:17 example.com platform-python[597336]: ansible-containers.podman.podman_container PODMAN-CONTAINER-DEBUG: podman rm -f test
Jan 10 02:12:17 example.com systemd[1131]: container-test.service: Service RestartSec=100ms expired, scheduling restart.
Jan 10 02:12:17 example.com systemd[1131]: container-test.service: Scheduled restart job, restart counter is at 2.
Jan 10 02:12:17 example.com systemd[1131]: Stopped Podman container-test.service.
Jan 10 02:12:17 example.com systemd[1131]: Starting Podman container-test.service...
Jan 10 02:12:17 example.com systemd[1131]: Started Podman container-test.service.
Jan 10 02:12:17 example.com podman[597668]: 83c32faf04d7d1f6a8dcf6aae0b0b0c8634db67758c1cc067f574b6971473bad
```

I tried reproducing with `alpine:latest`, but didn't have any issues. I suspect this issue crops up with containers that are slower to start/stop. I get the same error whether the state is created, present, or started. Here's my test playbook that fails 100% of the time.
```yaml
- hosts: localhost
  gather_facts: false
  become: true
  become_user: '{{ container_user }}'
  tasks:
    - name: create test container
      containers.podman.podman_container:
        name: test
        image: docker.io/vaultwarden/server:alpine
        generate_systemd:
          new: true
          no_header: true
          path: '/home/{{ container_user }}/.config/systemd/user/'
        state: present
        recreate: false

    - name: start/enable container services
      systemd:
        daemon-reload: true
        name: container-test
        state: started
        enabled: true
        scope: user
```

* host OS: Rocky Linux 8.5
* podman: 3.3.1
* ansible: 2.12.1
* containers.podman: 1.9.0 (also tested with 1.8.3)

There are two issues I see here.
1. The module is needlessly stopping, removing, and recreating the container.
2. The container removal fails.

The latter might be the easier problem to fix: `podman rm --ignore`. The former is probably a logic bug somewhere. Unfortunately it's much too late for me to start digging into the code right now. Perhaps this week.

**Comment by sshnaidm** [comment] 2022-01-10 12:56
I don't think it's module that removes the container, probably it's a systemd action. I still don't understand the purpose of `--new` in context of podman ansible module and what is its usage.

**Comment by 31239899** [comment] 2022-01-10 13:36
> I don't think it's module that removes the container, probably it's a systemd action.

Please note these two lines from my system logs above:
```
Jan 10 02:12:16 example.com platform-python[597336]: ansible-containers.podman.podman_container PODMAN-CONTAINER-DEBUG: podman stop test
Jan 10 02:12:17 example.com platform-python[597336]: ansible-containers.podman.podman_container PODMAN-CONTAINER-DEBUG: podman rm -f test
```
And also the `--diff --check` output:
```
TASK [create test container] ***************************************************
--- before
+++ after
@@ -1 +1 @@
-rm - True
+rm - False
```
Either the module is removing the container or it is outputting incorrect information.

> I still don't understand the purpose of `--new` in context of podman ansible module and what is its usage.

Using `--new` removes the container when the service is stopped and recreates it when the service is started. Among other things, this allows one to use `podman auto-update` to pull down the latest images and restart containers. Here's a diff of a service file without and with `--new`.

```diff
diff --git a/without-new b/with-new
index af2c812..0e33d04 100644
--- a/without-new
+++ b/with-new
@@ -5,17 +5,18 @@ Description=Podman container-05bb100303c8c774e5c05ad8a8056a66b07085e98af75850c1c
 Documentation=man:podman-generate-systemd(1)
 Wants=network-online.target
 After=network-online.target
-RequiresMountsFor=/run/user/1000/containers
+RequiresMountsFor=%t/containers
 
 [Service]
 Environment=PODMAN_SYSTEMD_UNIT=%n
 Restart=on-failure
 TimeoutStopSec=70
-ExecStart=/usr/bin/podman start 05bb100303c8c774e5c05ad8a8056a66b07085e98af75850c1cd17a935812930
-ExecStop=/usr/bin/podman stop -t 10 05bb100303c8c774e5c05ad8a8056a66b07085e98af75850c1cd17a935812930
-ExecStopPost=/usr/bin/podman stop -t 10 05bb100303c8c774e5c05ad8a8056a66b07085e98af75850c1cd17a935812930
-PIDFile=/run/user/1000/containers/overlay-containers/05bb100303c8c774e5c05ad8a8056a66b07085e98af75850c1cd17a935812930/userdata/conmon.pid
-Type=forking
+ExecStartPre=/bin/rm -f %t/%n.ctr-id
+ExecStart=/usr/bin/podman container run --cidfile=%t/%n.ctr-id --sdnotify=conmon --cgroups=no-conmon --rm -d --replace --name vaultwarden --healthcheck-command /healthcheck.sh --healthcheck-interval 60s --healthcheck-timeout 10s --http-proxy=False --no-hosts=True --label io.containers.autoupdate=registry --user 1000 docker.io/vaultwarden/server:alpine
+ExecStop=/usr/bin/podman stop --ignore --cidfile=%t/%n.ctr-id
+ExecStopPost=/usr/bin/podman rm -f --ignore --cidfile=%t/%n.ctr-id
+Type=notify
+NotifyAccess=all
 
 [Install]
 WantedBy=multi-user.target default.target
```

**Comment by sshnaidm** [comment] 2022-01-10 13:52
@31239899 I see, that's the podman_container module removes the container - but it does everything right, because container is created different, with `--rm`:
`+ExecStart=/usr/bin/podman container run --cidfile=%t/%n.ctr-id --sdnotify=conmon --cgroups=no-conmon --rm -d --replace --name vaultwarden --healthcheck-command /healthcheck.sh --healthcheck-interval 60s --healthcheck-timeout 10s --http-proxy=False --no-hosts=True --label io.containers.autoupdate=registry --user 1000 docker.io/vaultwarden/server:alpine`
And your configuration in task doesn't have `rm: true`. So containers are different and module replaces it due to discovered difference between existing one and configured in task.

**Comment by 31239899** [comment] 2022-01-10 14:39
@sshnaidm Thank you for pointing that out. Adding `rm: true` fixes the issue I had of recreating the container on every run. I don't find that behavior intuitive, but now that I know I can adjust accordingly. :) May I suggest that when `new=True`, `rm` should also be toggled to `True`, since that is the primary change with `podman generate systemd --new`? Or at least some documentation for `new` indicating that one must also set `rm`.

But in the case of a legitimate change (e.g. adding a port), the module still fails when it tries to remove the existing container because it has already been removed by systemd prior to restart the service. Just playing around with the code, even adding `--ignore` to the [delete command](https://github.com/containers/ansible-podman-collections/blob/master/plugins/module_utils/podman/podman_container_lib.py#L230) will still result in failure because systemd will recreate the container before the module can and we instead get "Error: error creating container storage: the container name XYZ is already in use".

For anyone else hitting this, an ugly workaround for now is to duplicate the task. Run the first one in check mode. If changed, stop the service. I'd probably put the task into a separate file and import it, so you don't have to worry about maintaining duplicate code.

```yaml
- hosts: localhost
  gather_facts: false
  become: true
  become_user: '{{ container_user }}'
  tasks:
    - name: create test container (check mode)
      containers.podman.podman_container:
        name: test
        image: docker.io/vaultwarden/server:alpine
        generate_systemd:
          new: true
          no_header: true
          path: '/home/{{ container_user }}/.config/systemd/user/'
        state: present
        rm: true
        recreate: false
      register: test
      check_mode: true

    - name: stop container service
      systemd:
        daemon-reload: true
        name: container-test
        state: stopped
        scope: user
      when: test.changed

    - name: create test container
      containers.podman.podman_container:
        name: test
        image: docker.io/vaultwarden/server:alpine
        generate_systemd:
          new: true
          no_header: true
          path: '/home/{{ container_user }}/.config/systemd/user/'
        state: present
        rm: true
        recreate: false

    - name: start/enable container service
      systemd:
        daemon-reload: true
        name: container-test
        state: started
        enabled: true
        scope: user
```

**Comment by sshnaidm** [comment] 2022-01-10 14:52
> May I suggest that when new=True, rm should also be toggled to True, since that is the primary change with podman generate systemd --new? Or at least some documentation for new indicating that one must also set rm.

Yes, it's totally possible. Although seems like ansible module and systemd will still have conflict in container management here. I'm open to suggestions what can be done here to make this work smoothly. If container management will be by systemd, probably we need only to `create` containers w/o running them?

**Comment by 31239899** [comment] 2022-01-10 17:01
I agree there's a conflict. I was hoping someone else would see a simple solution, but I couldn't come up with anything immediately. When `generate_systemd.new==False`, we'd need to create the container so systemd can start/stop it. But if `generate_systemd.new==True`, then I think it makes sense to only define the service file because systemd is now responsible for container creation on service start.

This whole thing also gets more complicated when we consider `state==absent`. I think that currently only deletes the container. But it could be recreated by systemd, depending on the value of `new`. Perhaps it should also delete the service file. But deleting the file without stopping the service and reloading systemd units will result in the unit continuing to run in memory. Very messy.

I don't have good answers right now, just brainstorming. I'll keep thinking about it. I believe the problems can be solved, but I don't know what level of complexity is worth adding.

**Comment by jeefberkey** [comment] 2022-01-10 17:10
Maybe it's time for a new module? `container.podman.podman_systemd_container` that will make all of these assumptions already.

**Comment by misuto** [comment] 2022-06-26 10:42
> @sshnaidm Thank you for pointing that out. Adding `rm: true` fixes the issue I had of recreating the container on every run. I don't find that behavior intuitive, but now that I know I can adjust accordingly. :) May I suggest that when `new=True`, `rm` should also be toggled to `True`, since that is the primary change with `podman generate systemd --new`? Or at least some documentation for `new` indicating that one must also set `rm`.
> 
> But in the case of a legitimate change (e.g. adding a port), the module still fails when it tries to remove the existing container because it has already been removed by systemd prior to restart the service. Just playing around with the code, even adding `--ignore` to the [delete command](https://github.com/containers/ansible-podman-collections/blob/master/plugins/module_utils/podman/podman_container_lib.py#L230) will still result in failure because systemd will recreate the container before the module can and we instead get "Error: error creating container storage: the container name XYZ is already in use".
> 
> For anyone else hitting this, an ugly workaround for now is to duplicate the task. Run the first one in check mode. If changed, stop the service. I'd probably put the task into a separate file and import it, so you don't have to worry about maintaining duplicate code.
> 
> ```yaml
> - hosts: localhost
>   gather_facts: false
>   become: true
>   become_user: '{{ container_user }}'
>   tasks:
>     - name: create test container (check mode)
>       containers.podman.podman_container:
>         name: test
>         image: docker.io/vaultwarden/server:alpine
>         generate_systemd:
>           new: true
>           no_header: true
>           path: '/home/{{ container_user }}/.config/systemd/user/'
>         state: present
>         rm: true
>         recreate: false
>       register: test
>       check_mode: true
> 
>     - name: stop container service
>       systemd:
>         daemon-reload: true
>         name: container-test
>         state: stopped
>         scope: user
>       when: test.changed
> 
>     - name: create test container
>       containers.podman.podman_container:
>         name: test
>         image: docker.io/vaultwarden/server:alpine
>         generate_systemd:
>           new: true
>           no_header: true
>           path: '/home/{{ container_user }}/.config/systemd/user/'
>         state: present
>         rm: true
>         recreate: false
> 
>     - name: start/enable container service
>       systemd:
>         daemon-reload: true
>         name: container-test
>         state: started
>         enabled: true
>         scope: user
> ```

Sorry for reviving this issue. @31239899 Do you have any help you could give in regards to how this workaround could be used as a task? Can I replace the role parameters with variables, and if possible, how do I do that?

**Comment by 31239899** [comment] 2022-06-27 21:14
@misuto, I'm not sure if I understand your question. Are you asking how to call the four tasks I included as a single task? You could put them in their own task file and `include_tasks` or `import_tasks`. You could even make it its own role and include that, I suppose. For either, you can use variables as you normally would in Ansible to supply the values you want.

If you are asking something else, perhaps you can rephrase the question for me.

**Comment by misuto** [comment] 2022-06-28 12:18
> @misuto, I'm not sure if I understand your question. Are you asking how to call the four tasks I included as a single task? You could put them in their own task file and `include_tasks` or `import_tasks`. You could even make it its own role and include that, I suppose. For either, you can use variables as you normally would in Ansible to supply the values you want.
> 
> If you are asking something else, perhaps you can rephrase the question for me.

@31239899 The question is about making the workaround easily reusable. I tried to use put the workaround you suggested in a tasks file and include/import it with both `include_tasks` and `import_tasks`, but I was not able to get the variables passed correctly. If I understand ansible correctly the way the arguments are passed in the workaround to the podman role, is with role parameters. Is there some way that these can be changed to take variables instead so that the tasks file can be included or imported and variables only needs to be set there?  
Something like this:  
```yaml
- name: Create Traefik container
  include_tasks:
    file: container.yml
    apply:
      vars:
        name: traefik
        image: docker.io/library/traefik
        cpu_shares: 1024
        memory: 100000000 # 100M
        <more variables here>
```
I hope the question is more clear now, thank you for your patience with me :slightly_smiling_face: I'm still new to ansible.

**Comment by 31239899** [comment] 2022-06-28 14:43
@misuto, I understand now. You can format it like this, without `apply`.
```yaml
- name: Create Traefik container
  include_tasks:
    file: container.yml
  vars:
    name: traefik
    image: docker.io/library/traefik
    ...
```
Although if you repeat all of the vars for two includes, you might as well just put the original tasks inline since you're not avoiding duplication.

I'm fairly sure you can set `check_mode` using a variable, but you'll want to verify that. So what I would try is keeping the stuff that doesn't change (name, image, etc.) in the file to be included and just use a variable to toggle `check_mode`. You'll probably need to use `check_mode: '{{ set_check_mode|default(omit) }}'` in the include, since the task-level setting overrides the one provided on the CLI.

```yaml
- name: Create Traefik container (check mode)
  include_tasks: container.yml
  vars:
    set_check_mode: true

- name: stop container
  service:
    ...
  when: registered_var_from_included_file.changed

- name: Create Traefik container
  include_tasks: container.yml
```

This is an easier and possibly better way, although I believe Ansible will warn about it. Make sure you understand the [possible security implications](https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#when-is-it-unsafe-to-bulk-set-task-arguments-from-a-variable) of this method.

```yaml
- name: create container (check mode)
  containers.podman.podman_container: {{ container_args }}
  check_mode: true
  register: container_check

- name: stop container
  service:
  ...
  when: container_check.changed

- name: create container
  containers.podman.podman_container: {{ container_args }}
```

Where `container_args` is everything you'd pass to `podman_container`. Example:
```yaml
container_args:
  name: traefik
  image: docker.io/library/traefik
  cpu_shares: 1024
  memory: 100000000 # 100M
```

**Comment by misuto** [comment] 2022-07-10 14:49
@31239899 Sorry for the late reply. This is exactly what I wanted to do. I went with the second option and managed to disable 
the `INJECT_FACTS_AS_VARS` config option after some adjustments. Thank you for the help and clarifications to make this work for me!

**Comment by sshnaidm** [comment] 2023-08-12 12:03
Reopen it if wasn't fixed by https://github.com/containers/ansible-podman-collections/pull/542

**Closed by sshnaidm** 2023-08-12 12:03 UTC
Labels: bug
